spring.application.name=todoapp
spring.profiles.active=dev

server.port=8080
server.error.include-stacktrace=ALWAYS 
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/todo
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.show-sql=true